openapi: 3.0.1
info:
  description: Sekvensanalyseplatform
  title: SAP
  version: 0.1.0
servers:
- url: http://localhost:8080/api/
tags:
- description: Operations about user
  name: user
- description: Operations for isolates
  name: analysis
paths:
  /analysis:
    get:
      description: Page through all the analysis in the system (WIP)
      operationId: get_analysis
      parameters:
      - description: opaque token to supply to get the next page of isolates
        explode: true
        in: query
        name: paging_token
        required: false
        schema:
          format: byte
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: page_size
        required: false
        schema:
          default: 100
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'
          description: Page of isolates
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
    post:
      description: Search all analysis by given query
      operationId: search_analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'
          description: Page of isolates
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: query
  /analysis/changes:
    post:
      description: Submit a batch of analysis data changes
      operationId: submit_changes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisChange'
      responses:
        "204":
          description: Changes accepted
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
  /analysis/columns:
    get:
      description: Get column metadata, scoped to authenticated user
      operationId: get_columns
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Column'
                type: array
          description: Column collection
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
  /approvals:
    get:
      description: Retrieve list of approvals for authenticated user
      operationId: get_approvals
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Approval'
                type: array
          description: List of Approvals
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
    post:
      description: Submit approval/rejection information
      operationId: create_approval
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approval'
          description: Approval accepted
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      x-codegen-request-body-name: body
  /approvals/{id}:
    delete:
      description: Cancel a pending approval
      operationId: cancel_approval
      parameters:
      - description: Id of approval to cancel
        explode: true
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Approval cancelled successfully.
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
  /user/views:
    get:
      operationId: get_user_views
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserDefinedView'
                type: array
          description: Return user-defined view collection for the authenticated user
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
    post:
      operationId: create_user_view
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDefinedView'
      responses:
        "204":
          description: User-defined view created.
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /user/views/{name}:
    delete:
      description: Delete an existing view
      operationId: delete_view
      parameters:
      - description: Name of view to delete
        explode: true
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: View deleted successfully.
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
components:
  schemas:
    Organization:
      enum:
      - SSI
      - FVST
      type: string
    PageOfAnalysis:
      example:
        paging_token: paging_token
        approval_matrix:
          key:
            key: approval_matrix
        total_count: 0
        items:
        - null
        - null
      properties:
        paging_token:
          nullable: true
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
        total_count:
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AnalysisResult'
          type: array
        approval_matrix:
          additionalProperties:
            additionalProperties:
              $ref: '#/components/schemas/ApprovalStatus'
            type: object
          type: object
      required:
      - approval_matrix
      - items
      - paging_token
      - total_count
    AnalysisQuery:
      example:
        paging_token: paging_token
        filters:
          key: filters
        page_size: 0
      properties:
        paging_token:
          description: opaque token to supply to get the next page of isolates
          format: byte
          nullable: true
          type: string
        page_size:
          default: 100
          nullable: true
          type: integer
        filters:
          additionalProperties:
            type: string
          type: object
    Column:
      example:
        pii: true
        approves_with:
        - approves_with
        - approves_with
        approvable: true
        editable: true
        organizations:
        - null
        - null
        field_name: field_name
      properties:
        approvable:
          type: boolean
        editable:
          type: boolean
        pii:
          type: boolean
        organizations:
          items:
            $ref: '#/components/schemas/Organization'
          type: array
        field_name:
          type: string
        approves_with:
          items:
            type: string
          type: array
    UserDefinedView:
      example:
        hiddenColumns:
        - hiddenColumns
        - hiddenColumns
        columnOrder:
        - columnOrder
        - columnOrder
        name: name
        sortBy:
        - id: id
          desc: true
        - id: id
          desc: true
        columnResizing:
          columnWidth: 6
          columnWidths:
          - width: 0
            columnName: columnName
          - width: 0
            columnName: columnName
      properties:
        name:
          type: string
        hiddenColumns:
          items:
            type: string
          type: array
        columnResizing:
          $ref: '#/components/schemas/UserDefinedView_columnResizing'
        sortBy:
          items:
            $ref: '#/components/schemas/UserDefinedView_sortBy'
          type: array
        columnOrder:
          items:
            type: string
          type: array
      type: object
    ApprovalRequest:
      example:
        matrix:
          key:
            key: matrix
      properties:
        matrix:
          additionalProperties:
            additionalProperties:
              $ref: '#/components/schemas/ApprovalStatus'
            type: object
          type: object
      required:
      - matrix
      type: object
    Approval:
      allOf:
      - $ref: '#/components/schemas/ApprovalRequest'
      - $ref: '#/components/schemas/Approval_allOf'
    ApprovalStatus:
      enum:
      - pending
      - rejected
      - approved
      type: string
    ApprovalMatrix:
      additionalProperties:
        additionalProperties:
          $ref: '#/components/schemas/ApprovalStatus'
        type: object
      type: object
    AnalysisChange:
      additionalProperties:
        additionalProperties:
          type: string
        type: object
      type: object
    Resistance:
      enum:
      - Sensitiv
      - Resistent
      - Ukendt
      type: string
    BaseMetadata:
      properties:
        isolate_id:
          type: string
        sequence_id:
          type: string
        sequence_filename:
          type: string
        institution:
          $ref: '#/components/schemas/Organization'
        project_number:
          type: number
        project_title:
          type: string
        sampling_date:
          format: date-time
          type: string
        received_date:
          format: date-time
          type: string
        run_id:
          type: string
        public:
          type: string
        provided_species:
          type: string
        primary_isolate:
          type: boolean
      required:
      - institution
      - isolate_id
      - primary_isolate
      - provided_species
      - received_date
      - run_id
      - sequence_filename
      - sequence_id
    TbrSpecificMetadata:
      properties:
        cpr:
          pattern: ^(?:(?:31(?:0[13578]|1[02])|(?:30|29)(?:0[13-9]|1[0-2])|(?:0[1-9]|1[0-9]|2[0-8])(?:0[1-9]|1[0-2]))[0-9]{2}\s?-?\s?[0-9]|290200\s-?\s[4-9]|2902(?:(?!00)[02468][048]|[13579][26])\s?-?\s?[0-3])[0-9]{3}|000000\s?-?\s?0000$
          type: string
        gender:
          enum:
          - M
          - K
          type: string
        name:
          type: string
          x-faker: name.findName
        age:
          maximum: 128
          minimum: 0
          type: integer
        travel:
          type: string
        travel_country:
          type: string
          x-faker: address.country
        run_date:
          format: date-time
          type: string
        kma_received_date:
          format: date-time
          type: string
        kma:
          type: string
        region:
          type: string
        fud_number:
          type: string
        cluster_id:
          type: string
        epi_export:
          type: string
      required:
      - run_date
      type: object
    TbrMetadata:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/TbrSpecificMetadata'
    LimsSpecificMetadata:
      properties:
        chr_number:
          pattern: \d{5,6}
          type: string
        aut_number:
          type: string
        product_type:
          type: string
        product:
          type: string
        origin_country:
          type: string
          x-faker: address.country
        animal_species:
          type: string
        sample_info:
          type: string
      type: object
    LimsMetadata:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/LimsSpecificMetadata'
    AnalysisResult:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/LimsSpecificMetadata'
      - $ref: '#/components/schemas/TbrSpecificMetadata'
      - $ref: '#/components/schemas/AnalysisResult_allOf'
    UserDefinedView_columnResizing_columnWidths:
      example:
        width: 0
        columnName: columnName
      properties:
        columnName:
          type: string
        width:
          type: integer
    UserDefinedView_columnResizing:
      example:
        columnWidth: 6
        columnWidths:
        - width: 0
          columnName: columnName
        - width: 0
          columnName: columnName
      properties:
        columnWidths:
          items:
            $ref: '#/components/schemas/UserDefinedView_columnResizing_columnWidths'
          type: array
        columnWidth:
          type: integer
    UserDefinedView_sortBy:
      example:
        id: id
        desc: true
      properties:
        desc:
          type: boolean
        id:
          type: string
    Approval_allOf:
      properties:
        id:
          type: string
        approver:
          type: string
        timestamp:
          format: date-time
          type: string
        status:
          enum:
          - pending
          - cancelled
          - submitted
          type: string
    AnalysisResult_allOf:
      properties:
        _id:
          format: uuid
          type: string
        resfinder_version:
          pattern: ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$
          type: string
        QC_provided_species:
          type: number
        QC_genome1x:
          type: number
        QC_genome10x:
          type: number
        QC_Gsize_diff1x10:
          type: number
        QC_Avg_coverage:
          type: number
        QC_final:
          enum:
          - A
          - B
          - C
          type: string
        subspecies:
          type: string
        species_final:
          type: string
        st:
          type: string
        pathotype:
          type: string
        pathotype_final:
          type: string
        serotype:
          type: string
        serotype_final:
          type: string
        adhesion:
          type: string
        toxins:
          type: string
        resistance_genes:
          type: string
        amr_profile:
          type: string
        amr_ami:
          $ref: '#/components/schemas/Resistance'
        amr_amp:
          $ref: '#/components/schemas/Resistance'
        amr_azi:
          $ref: '#/components/schemas/Resistance'
        amr_fep:
          $ref: '#/components/schemas/Resistance'
        amr_fot:
          $ref: '#/components/schemas/Resistance'
        amr_f_c:
          $ref: '#/components/schemas/Resistance'
        amr_fox:
          $ref: '#/components/schemas/Resistance'
        amr_taz:
          $ref: '#/components/schemas/Resistance'
        amr_t_c:
          $ref: '#/components/schemas/Resistance'
        amr_chl:
          $ref: '#/components/schemas/Resistance'
        amr_cip:
          $ref: '#/components/schemas/Resistance'
        amr_cli:
          $ref: '#/components/schemas/Resistance'
        amr_col:
          $ref: '#/components/schemas/Resistance'
        amr_dap:
          $ref: '#/components/schemas/Resistance'
        amr_etp:
          $ref: '#/components/schemas/Resistance'
        amr_ery:
          $ref: '#/components/schemas/Resistance'
        amr_fus:
          $ref: '#/components/schemas/Resistance'
        amr_gen:
          $ref: '#/components/schemas/Resistance'
        amr_imi:
          $ref: '#/components/schemas/Resistance'
        amr_kan:
          $ref: '#/components/schemas/Resistance'
        amr_lzd:
          $ref: '#/components/schemas/Resistance'
        amr_mero:
          $ref: '#/components/schemas/Resistance'
        amr_mup:
          $ref: '#/components/schemas/Resistance'
        amr_nal:
          $ref: '#/components/schemas/Resistance'
        amr_pen:
          $ref: '#/components/schemas/Resistance'
        amr_syn:
          $ref: '#/components/schemas/Resistance'
        amr_rif:
          $ref: '#/components/schemas/Resistance'
        amr_str:
          $ref: '#/components/schemas/Resistance'
        amr_sul:
          $ref: '#/components/schemas/Resistance'
        amr_tei:
          $ref: '#/components/schemas/Resistance'
        amr_trm:
          $ref: '#/components/schemas/Resistance'
        amr_tet:
          $ref: '#/components/schemas/Resistance'
        amr_tia:
          $ref: '#/components/schemas/Resistance'
        amr_tgc:
          $ref: '#/components/schemas/Resistance'
        amr_tmp:
          $ref: '#/components/schemas/Resistance'
        amr_van:
          $ref: '#/components/schemas/Resistance'
      required:
      - _id
      - isolate_id
  securitySchemes:
    SAP_auth:
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller_.info_from_SAP_auth
